DROP TABLE IF EXISTS Cities;
DROP TABLE IF EXISTS CityConnections;
DROP TABLE IF EXISTS CityAliases;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Tokens;
DROP TABLE IF EXISTS Guides;
DROP TABLE IF EXISTS GuideReservations;
DROP TABLE IF EXISTS GuideLanguages;
DROP TABLE IF EXISTS GuideLocations;
DROP TABLE IF EXISTS GuideBillingMethods;
DROP TABLE IF EXISTS Orders;  --
DROP TABLE IF EXISTS Photos;
DROP TABLE IF EXISTS Locations;
DROP TABLE IF EXISTS Levels;
DROP TABLE IF EXISTS Languages;
DROP TABLE IF EXISTS BillingMethods;
